Fetch HTTPS
Jigsaw-Code/outline-apps pull request #1008
Opened 2021-04-15 23:50 UTC by alalamav

- Implements functionality to natively fetch HTTPs data on all platforms.
  - The motivation behind this change is to provide the infrastructure to support dynamic access keys (online config).
- Supports self-signed certificates through a pinned certificate fingerprint.
- Does not automatically follow HTTP redirects.
- Defines error types and codes for failure conditions.
- This code is currently not called by the web app.

2021-04-16 17:19 UTC, JonathanDCohen commented on src/electron/https.ts
> +  const validateServerCertificate = !!request.hexSha256CertFingerprint;
Nit: we only ever use `!validateServerCertificate`, so maybe this could be `invalidServerCertificate` instead to slightly simplify

2021-04-16 21:03 UTC, fortuna requested changes
Ugh, this is such a pain. It makes me think that having a side service reachable from JS may not be a bad idea.
I think we can simplify and expand error handling to have one config fetch error + detail string.

2021-04-16 21:03 UTC, fortuna commented on cordova-plugin-outline/android/java/org/outline/OutlinePlugin.java
> +            ErrorCode errorCode = ErrorCode.UNEXPECTED;
I think we should simplify our error handling.

I was imagining a very simple UI that says "Failed to fetch config (MalformedURLException)" or "Failed to fetch config (ECONNREFUSED)"

All you should need to pass from the native and Electron code to the webview code is a generic FetchConfigError and a string.

For Java, you could return the name of the error. For Node we could return the code.
This simplifies the error handling, and also captures the "unexpected" cases, which are the ones we probably want to find out more about.

2021-04-16 22:04 UTC, JonathanDCohen commented on src/www/app/net.ts
> +  // HEX encoded SHA-256 certificate hash to pin as a trusted TLS certificate.
If we go base64 we need to do the url-safe version of it

2021-04-21 21:08 UTC, alalamav commented on src/www/app/net.ts
> +  // HEX encoded SHA-256 certificate hash to pin as a trusted TLS certificate.
Makes sense to keep a consistent format. My thinking was that all those colons are unnecessary, particularly in platforms where we are treating the data as bytes (apple, android).

Done in ffc4f25, anyway.

2021-04-21 21:09 UTC, alalamav commented on src/electron/https.ts
> +    const hexSha256CertFingerprint = cert.fingerprint256.replace(/:/g, '');
Done in ffc4f25.

2024-03-05 22:07 UTC, closed without merging