refactor(infrastructure): move infrastructure code to its own package
Jigsaw-Code/outline-apps pull request #1985
Opened 2024-04-19 22:07 UTC by sbruens

2024-04-19 22:46 UTC, fortuna requested changes

2024-04-19 22:46 UTC, fortuna commented on .gitignore
> +/infrastructure/dist
Why is this?

2024-04-19 22:46 UTC, fortuna commented on client/package.json
> +    "outline-infrastructure": "file:../infrastructure",
Perhaps `@outline/infrastructure`?

2024-04-19 22:46 UTC, fortuna commented on infrastructure/build.action.sh
Why does this have a build action? Tsc and webpack will follow the dependencies. We don't need to build it. We also won't consume the built library.

2024-04-19 22:46 UTC, fortuna commented on infrastructure/crypto.ts
> -export class KeyPair {
Revert. This is uses as a struct, not interfaces. I see interfaces with fields as an anti-pattern, since it forces implementation.

2024-04-19 22:46 UTC, fortuna commented on infrastructure/index.ts
Why is this?

2024-04-19 22:46 UTC, fortuna commented on infrastructure/package.json
> +  "files": [
Remove files, we don't need it.

2024-04-19 22:46 UTC, fortuna commented on infrastructure/test.action.sh
> +jasmine --config="${ROOT_DIR}/jasmine.json"
I don't think we need a jasmine config. It's probably easiest to just pass what you need in the command

2024-04-19 22:46 UTC, fortuna commented on infrastructure/test.webpack.js
Ugh, do we really want to build the tests? Why?

2024-04-19 22:46 UTC, fortuna commented on infrastructure/tsconfig.json
I'm not sure we need a tsconfig for infrastructure.

2024-04-22 19:13 UTC, sbruens commented
I made more changes. I think this is now ready for review.

2024-04-23 12:50 UTC, fortuna approved these changes
Looks great, thanks!

2024-04-23 12:50 UTC, fortuna commented on client/src/www/app/app.ts
> +import {OperationTimedOut} from '@outline/infrastructure/timeout_promise';
The problem with the re-exporting things on an top-level index file is that you lose the namespacing from the subdirectories, making it possible to have collisions and unclear where things are coming from. You import a bunch of things you don't need. I also find it confusing to have two different places to import the same code.

2024-04-23 12:50 UTC, fortuna commented on client/src/www/app/app.ts
> +import {OperationTimedOut} from '@outline/infrastructure/timeout_promise';
@daniellacosse I don't see any extra moves happening.

2024-04-23 14:12 UTC, merged